### ISSUE TITLE
Create jenkins user before installing the package with manage_user

### ISSUE THREAD

**Issue by vStone** [voxpupuli/puppet-jenkins#462]
The usermod fails when using a custom localestatedir value due to jenkins already running after installation (debian-ish systems are 'cool' like that)

```
==> jenkins: Notice: /Stage[main]/Jenkins::Package/Package[jenkins]/ensure: ensure changed 'purged' to 'present'
==> jenkins: Error: Could not set home on user[jenkins]: Execution of '/usr/sbin/usermod -d /data/jenkins jenkins' returned 8: usermod: user jenkins is currently used by process 17664
==> jenkins: Error: /Stage[main]/Jenkins::Config/User[jenkins]/home: change from /var/lib/jenkins to /data/jenkins failed: Could not set home on user[jenkins]: Execution of '/usr/sbin/usermod -d /data/jenkins jenkins' returned 8: usermod: user jenkins is currently used by process 17664
```

**Comment by vStone** [comment]
I also noticed that setting the localstatedir does not automatically change the JENKINS_HOME using jenkins::sysconfig. Is this intended behaviour?

**Comment by jhoblitt** [comment]
@vStone I'm not sure what we could do here except not manage the jenkins user on debian?

**Comment by vStone** [comment]
Perhaps: https://github.com/vrtdev/puppet-jenkins/commit/88431d38b005a59b59b998b6481dc18279a161a1

**Comment by boyand** [comment]
:+1:

**Comment by GuitarrasDeAmor** [comment]
I've run into this problem on CentOS 7. Weirdly enough I cannot produce it locally but consistently fails on the box I am spinning up within AWS. My only workaround is to create the user before Puppet runs -- if I don't, then I cannot create the user after because the system seems to think that it is created even though it is not in /etc/passwd, and trying to delete it says the user doesn't exist, so in turn the initial failure seems to break everything related to that user for me.
